### PR TITLE
Fixed Target2 not firing on func_door.

### LINKED ISSUE #64: target2 key on func_door not working
Per the title, it seems as though the `target2` key on `func_door` is not working. It is commonly used for the door closing sound by targeting a `target_speaker`

Per the documenation, the `target2` should be called when the func_door begins to close.

```
target              : door fires this when it starts moving from its closed position.
opentarget          : Door fires this after reaching its open position
target2             : Door fires this when it starts moving from it's open position to its closed position.
closetarget         : Door fires this after reaching its closed position.
```

For an example, you can see on our new `mp/ctf1` build on the exterior doors into the Dantooine Enclave, I have the door opening sound set to target and `target2` so that it will play the sound when the door opens and when it closes, but it only plays the opening sound. We have tried a bunch of things to work it out, including using a different `target_speaker` for `target2` but nothing works. Likewise, `closetarget` is working as expected and playing the sound when the closing animation finishes.

### PR DESCRIPTION
**Pull request by lumayaa**
target2 - Door fires this when it starts moving from it's open position to its closed position.

### CODE REVIEW

File: game/g_mover.c [hunk 1]
```diff
@@ -663,6 +663,12 @@ void ReturnToPos1( gentity_t *ent ) {
 	ent->nextthink = 0;
 	ent->s.time = level.time;
 
+	if ( ent->target2 && ent->target2[0] )
+	{
+		gentity_t *activator = ent->activator ? ent->activator : ent;
+		G_UseTargets2( ent, activator, ent->target2 );
```
Comment (slash-fr) [inline game/g_mover.c:669]: This looks like the correct place to put `G_UseTargets2( ent, activator, ent->target2 );` 👍

We should remove the old one from line 812, because it gets called immediately when the door is used while open (`MOVER_POS2`) instead of waiting for the call to `ReturnToPos1()`. *(Noticeable when spawnflag 8 [MOVER_TOGGLE] is OFF).*

Comment (lumayaa) [reply game/g_mover.c:669]: It was never called idk about this function but it doesn't seem to work

Comment (slash-fr) [reply game/g_mover.c:669]: Here's a test, with the current code from this PR:
```
{
"classname" "misc_model_breakable"
"model" "map_objects/desert/switch_locked"
"spawnflags" "97"
"origin" "-1695 5001 45"
"target" "tournydoor"
}
{
"classname" "func_door"
"model" "*43"
"origin" "-20 0 0"
"targetname" "tournydoor"
"spawnflags" "8"
"angle" "-1"
"lip" "57"
"target2" "door_starts_closing"
}
{
"classname" "target_print"
"targetname" "door_starts_closing"
"message" "The door is closing..."
}
```

https://github.com/user-attachments/assets/12e5e620-f3ea-4dd9-8ac0-0527734adf07

1. With `spawnflags 8` (MOVER_TOGGLE), the `target_print` message fires when the player closes the door, as expected. It fires twice at the same time, though (`g_mover.c:669` + `g_mover.c:812`).
2. With `spawnflags 0`, if the player lets the door close on its own, the `target_print` fires when the door starts closing, as expected (`g_mover.c:669`).
3. However, with `spawnflags 0`, the `target_print` also fires when the player "uses" the door while it's open (`g_mover.c:812`), which does *not* close the door (by design), but just keeps the door open for a little longer.

Comment (lumayaa) [reply game/g_mover.c:669]: 👍 removed the 2nd (old G_UseTargets2). So now only the new one fires.

**Review by slash-fr — APPROVED** [review]
